"""Init

Revision ID: 7c05d603ab2d
Revises: 
Create Date: 2026-03-01 23:33:10.323466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c05d603ab2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('article_number', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_type', sa.Enum('REGULAR', 'PROMO', name='pricetype'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_article_number'), 'prices', ['article_number'], unique=False)
    # ### end Alembic commands ###
    post_upgrade()


def downgrade():
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_article_number'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###


    post_downgrade()


def pre_upgrade():
    pass


def post_upgrade():

    pass


def pre_downgrade():
    pass


def post_downgrade():
    pass